document.writeln("<header>");
document.writeln("    <div class=\'header-top min-width\'>");
document.writeln("        <div class=\'container fn-clear\'> <strong class=\'fn-left\'>咨询热线：400-668-6698<span class=\'s-time\'>服务时间：9:00 - 18:00</span></strong>");
document.writeln("            <ul class=\'header_contact\'>");
document.writeln("                <li class=\'c_1\'> <a class=\'ico_head_weixin\' id=\'wx\'></a>");
document.writeln("                    <div class=\'ceng\' id=\'weixin_xlgz\' style=\'display: none;\'>");
document.writeln("                        <div class=\'cnr\'> <img src=\'images/code.png\'> </div>");
document.writeln("                        <b class=\'ar_up ar_top\'></b> <b class=\'ar_up_in ar_top_in\'></b> </div>");
document.writeln("                </li>");
document.writeln("                <li class=\'c_2\'><a href=\'#\' target=\'_blank\' title=\'官方QQ\' alt=\'官方QQ\'><b class=\'ico_head_QQ\'></b></a></li>");
document.writeln("                <li class=\'c_4\'><a href=\'#\' target=\'_blank\' title=\'新浪微博\' alt=\'新浪微博\'><b class=\'ico_head_sina\'></b></a></li>");
document.writeln("            </ul>");
document.writeln("            <ul class=\'fn-right header-top-ul\'>");
document.writeln("                <li> <a href=\'index\' class=\'app\'>返回首页</a> </li>");
document.writeln("                <!--<c:if test=\'${logininfo != null}\'>-->");
document.writeln("                    <li id=\'infoaccount\'>");
document.writeln("                        <div class=\'\'><a href=\'account.html\' class=\'c-orange\' title=\'我的账号\'>${logininfo.username}</a></div>");
document.writeln("                    </li>");
document.writeln("                    <li id=\'exit\'>");
document.writeln("                        <div class=\'\'><a href=\'logout\' class=\'js-login\' title=\'退出\'>退出</a></div>");
document.writeln("                    </li>");
document.writeln("                <!--</c:if>-->");
document.writeln("                <!--<c:if test=\'${logininfo == null}\'>-->");
document.writeln("                    <li id=\'register\'>");
document.writeln("                        <div class=\'\'><a href=\'register.html\' class=\'c-orange\' title=\'免费注册\'>免费注册</a></div>");
document.writeln("                    </li>");
document.writeln("                    <li id=\'login\'>");
document.writeln("                        <div class=\'\'><a href=\'login.html\' class=\'js-login\' title=\'登录\'>登录</a></div>");
document.writeln("                    </li>");
document.writeln("                <!--</c:if>-->");
document.writeln("");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'header min-width\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("            <div class=\'fn-left logo\'> <a class=\'\' href=\'index\'> <img src=\'images/logo.png\'  title=\'\'> </a> </div>");
document.writeln("            <ul class=\'top-nav fn-clear\'>");
document.writeln("                <li class=\'on\'> <a href=\'index.html\'>首页</a> </li>");
document.writeln("                <li> <a href=\'list.html\' class=\'\'>我要投资</a> </li>");
document.writeln("                <li> <a href=\'borrow.html\' class=\'\'>我要借款</a> </li>");
document.writeln("                <li> <a href=\'msghelp.html\'>安全保障</a> </li>");
document.writeln("                <!--<c:if test=\'${logininfo != null}\'>-->");
document.writeln("                    <li class=\'top-nav-safe\' id=\'userinfo\'> <a href=\'account\'>我的账户</a> </li>");
document.writeln("                <!--</c:if>-->");
document.writeln("                <li> <a href=\'公司简介.html\'>关于我们</a> </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</header>");