package com.qfedu.mapper.admin;

import com.qfedu.domain.admin.SysUser;

/**
 *@Author feri
 *@Date Created in 2018/7/29 23:41
 */
public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Mar 02 03:58:13 CST 2018
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Mar 02 03:58:13 CST 2018
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Mar 02 03:58:13 CST 2018
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Mar 02 03:58:13 CST 2018
     */
    SysUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Mar 02 03:58:13 CST 2018
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Mar 02 03:58:13 CST 2018
     */
    int updateByPrimaryKey(SysUser record);

    /**
     * 根据用户名，查询系统用户
     */
    SysUser queryByUserName(String username);
}
